### ISSUE TITLE
Inference on PYNQ Z2

### ISSUE THREAD

**Issue by Davorin51** [andre1araujo/YOLO-on-PYNQ-Z2#1]
Hello, I really like you work and it is pretty good structured, explained in detail which makes it easily available to use. I saw that you were using Petalinux and DNNDK. Do they work good in terms of inference time on pynq? I mean, what inference times did you get when running in C++? 
Didn't see it in gitbook tutorial, or maybe I missed something.

Thank you, and keep a good work

**Comment by Davorin51** [comment]
In fact those results are pretty good for pynq z2 board. I was doing something similar but with FINN-Brevitas framework to optimise, compile model in Python. But it was a slower for Yolo v3 tiny model with inference time of 0.072 seconds. Also, I would try to follow your steps, and get to know more about Petalinux, and especially interesting area around DPU (creation) in Vivado.

Thank you 😃

**Comment by andre1araujo** [comment]
Thank you very much!
I hope it all goes well for you, and if there's any problem let me know as I am still, in fact, making the finishing touches on the project documentation. 

Good work!
