### ISSUE TITLE
Errors after running petalinux build 

### ISSUE THREAD

**Issue by ghost** [andre1araujo/YOLO-on-PYNQ-Z2#12]
I tried running the petalinux build command and these errors occured:

<img width="928" alt="image" src="https://github.com/user-attachments/assets/8cc4ebb2-b3c6-447d-9609-be7da252295e">

can you help me with this?

the log:
<pre><font color="#8AE234"><b>mantra@Kendall</b></font>:<font color="#729FCF"><b>~</b></font>$ source /opt/petalinux/settings.sh
PetaLinux environment set to &apos;/opt/petalinux&apos;
INFO: Checking free disk space
INFO: Checking installed tools
INFO: Checking installed development libraries
INFO: Checking network and other services
WARNING: No tftp server found - please refer to &quot;PetaLinux SDK Installation Guide&quot; for its impact and solution
<font color="#8AE234"><b>mantra@Kendall</b></font>:<font color="#729FCF"><b>~</b></font>$ cd /home/mantra/Desktop
<font color="#8AE234"><b>mantra@Kendall</b></font>:<font color="#729FCF"><b>~/Desktop</b></font>$ cd dpu_integration/pynqz2_dpu/
<font color="#8AE234"><b>mantra@Kendall</b></font>:<font color="#729FCF"><b>~/Desktop/dpu_integration/pynqz2_dpu</b></font>$ petalinux-build
[INFO] building project
[INFO] sourcing bitbake
[INFO] generating user layers
[INFO] generating workspace directory
INFO: bitbake petalinux-user-image
Loading cache: 100% |############################################| Time: 0:00:03
Loaded 3980 entries from dependency cache.
Parsing recipes: 100% |##########################################| Time: 0:00:09
Parsing of 2894 .bb files complete (2893 cached, 1 parsed). 3981 targets, 169 skipped, 0 masked, 0 errors.
<b>NOTE</b>: Resolving any missing task queue dependencies
Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:19
Checking sstate mirror object availability: 100% |###########################################################################################################################################| Time: 0:01:27
Sstate summary: Wanted 846 Found 361 Missed 970 Current 1751 (42% match, 81% complete)
<b>NOTE</b>: Executing SetScene Tasks
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">Logfile for failed setscene task is /home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libfontenc/1_1.1.3-r0/temp/log.do_package_write_rpm_setscene.3543</font>
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">Setscene task (/opt/petalinux/components/yocto/source/arm/layers/core/meta/recipes-graphics/xorg-lib/libfontenc_1.1.3.bb:do_package_write_rpm_setscene) failed with exit code &apos;1&apos; - real task will be run instead</font>
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">Logfile for failed setscene task is /home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libxslt/1.1.32-r0/temp/log.do_package_qa_setscene.3777</font>
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">Setscene task (/opt/petalinux/components/yocto/source/arm/layers/core/meta/recipes-support/libxslt/libxslt_1.1.32.bb:do_package_qa_setscene) failed with exit code &apos;1&apos; - real task will be run instead</font>
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">Logfile for failed setscene task is /home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/socat/1.7.3.2-r0/temp/log.do_populate_lic_setscene.3951</font>
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">Setscene task (/opt/petalinux/components/yocto/source/arm/layers/core/meta/recipes-connectivity/socat/socat_1.7.3.2.bb:do_populate_lic_setscene) failed with exit code &apos;1&apos; - real task will be run instead</font>
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">Logfile for failed setscene task is /home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/x86_64-linux/libice-native/1_1.0.9-r0/temp/log.do_populate_sysroot_setscene.5433</font>
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">Setscene task (virtual:native:/opt/petalinux/components/yocto/source/arm/layers/core/meta/recipes-graphics/xorg-lib/libice_1.0.9.bb:do_populate_sysroot_setscene) failed with exit code &apos;1&apos; - real task will be run instead</font>
<b>NOTE</b>: Executing RunQueue Tasks
<font color="#FCE94F"><b>WARNING</b></font>: <font color="#C4A000">libfontenc-1_1.1.3-r0 do_fetch: Failed to fetch URL http://xorg.freedesktop.org/releases/individual/lib/libfontenc-1.1.3.tar.bz2, attempting MIRRORS if available</font>
<font color="#EF2929"><b>ERROR</b></font>: <font color="#CC0000">libfontenc-1_1.1.3-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS=&quot;unix:path=/run/user/1000/bus&quot;; export SSH_AGENT_PID=&quot;1659&quot;; export SSH_AUTH_SOCK=&quot;/run/user/1000/keyring/ssh&quot;; export GIT_SSL_CAINFO=&quot;/opt/petalinux/components/yocto/source/arm/buildtools/sysroots/x86_64-petalinux-linux/etc/ssl/certs/ca-certificates.crt&quot;; export PATH=&quot;/home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/opt/petalinux/components/yocto/source/arm/layers/core/scripts:/home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libfontenc/1_1.1.3-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi:/home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libfontenc/1_1.1.3-r0/recipe-sysroot/usr/bin/crossscripts:/home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libfontenc/1_1.1.3-r0/recipe-sysroot-native/usr/sbin:/home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libfontenc/1_1.1.3-r0/recipe-sysroot-native/usr/bin:/home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libfontenc/1_1.1.3-r0/recipe-sysroot-native/sbin:/home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libfontenc/1_1.1.3-r0/recipe-sysroot-native/bin:/opt/petalinux/tools/xsct/bin:/opt/petalinux/tools/xsct/gnu/microblaze/lin/bin:/opt/petalinux/tools/xsct/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/opt/petalinux/tools/xsct/gnu/armr5/lin/gcc-arm-none-eabi/bin:/opt/petalinux/tools/xsct/gnu/aarch64/lin/aarch64-none/bin:/opt/petalinux/components/yocto/source/arm/layers/core/bitbake/bin:/home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/hosttools&quot;; export HOME=&quot;/home/mantra&quot;; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/downloads &apos;http://xorg.freedesktop.org/releases/individual/lib/libfontenc-1.1.3.tar.bz2&apos; --progress=dot -v failed with exit code 4, output:</font>
<font color="#CC0000">--2024-08-07 06:54:05--  http://xorg.freedesktop.org/releases/individual/lib/libfontenc-1.1.3.tar.bz2</font>
<font color="#CC0000">Resolving xorg.freedesktop.org... 131.252.210.176</font>
<font color="#CC0000">Connecting to xorg.freedesktop.org|131.252.210.176|:80... failed: Connection timed out.</font>
<font color="#CC0000">Retrying.</font>

<font color="#CC0000">--2024-08-07 06:54:37--  (try: 2)  http://xorg.freedesktop.org/releases/individual/lib/libfontenc-1.1.3.tar.bz2</font>
<font color="#CC0000">Connecting to xorg.freedesktop.org|131.252.210.176|:80... failed: Connection timed out.</font>
<font color="#CC0000">Giving up.</font>

<font color="#EF2929"><b>ERROR</b></font>: <font color="#CC0000">libfontenc-1_1.1.3-r0 do_fetch: Fetcher failure for URL: &apos;http://xorg.freedesktop.org/releases/individual/lib/libfontenc-1.1.3.tar.bz2&apos;. Unable to fetch URL from any source.</font>
<font color="#EF2929"><b>ERROR</b></font>: <font color="#CC0000">libfontenc-1_1.1.3-r0 do_fetch: Function failed: base_do_fetch</font>
<font color="#EF2929"><b>ERROR</b></font>: <font color="#CC0000">Logfile of failure stored in: /home/mantra/Desktop/dpu_integration/pynqz2_dpu/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/libfontenc/1_1.1.3-r0/temp/log.do_fetch.15585</font>
<font color="#EF2929"><b>ERROR</b></font>: <font color="#CC0000">Task (/opt/petalinux/components/yocto/source/arm/layers/core/meta/recipes-graphics/xorg-lib/libfontenc_1.1.3.bb:do_fetch) failed with exit code &apos;1&apos;</font>
<b>NOTE</b>: Tasks Summary: Attempted 4805 tasks of which 3873 didn&apos;t need to be rerun and 1 failed.

Summary: 1 task failed:
  /opt/petalinux/components/yocto/source/arm/layers/core/meta/recipes-graphics/xorg-lib/libfontenc_1.1.3.bb:do_fetch
Summary: There was 1 WARNING message shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
ERROR: Failed to build project
</pre>

**Comment by andre1araujo** [comment]
Hello!
You cannot build the petalinux project without making the configurations. Is that what happened? You just accessed the directory and made build?
If following [this part](https://andre-araujo.gitbook.io/yolo-on-pynq-z2/dpu-implementation/implementing-the-dpu-on-a-sd-card-image#petalinux-project) of the tutorial led to that error, we have to investigate further.
It seems just that the program could not fetch one library from a URL. It leads me to **suspect that your internet connection was not working correctly at the time** because the URL exists and is functional.
I would try that again but making sure that the internet connection on the Virtual Machine is working right.
I hope this helps! If you make any progress let me know! :)

**Comment by ghost** [comment]
Yeah, we tried again and figured that issue was internet and we have
progressed to further steps.

Thank you.

**Comment by andre1araujo** [comment]
You are welcome!
If you find further issues, be sure to open a new issue as now I will be closing this one.
Good luck on the project!

**Comment by andre1araujo** [comment]
You are welcome!
If you find further issues, be sure to open a new issue as now I will be closing this one.
Good luck on the project!
